import Head from "next/head";
import Image from "next/image";
import { useCallback, useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

const Home = () => {
  const [title, setTitle] = useState("");

  const getPostTile = useCallback(async () => {
    const res = await fetch("http://localhost:3001/posts?auther=ken");
    const json = await res.json("");
    setTitle(json[0].title);
  }, []);

  useEffect(() => {
    getPostTile();
  }, [getPostTile]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Json server</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{title}</h1>
      </main>
    </div>
  );
};
export default Home;
